# Generated by Django 5.2.6 on 2025-10-11 13:28

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFormsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introductory text displayed above the groups/files.')),
            ],
            options={
                'verbose_name': 'Downloadable Forms Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the document.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional short description of the document.')),
                ('file', models.ForeignKey(help_text='Upload the document file (PDF, DOCX, etc.).', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='downloadables.downloadableformspage')),
            ],
            options={
                'verbose_name': 'Downloadable File',
                'verbose_name_plural': 'Downloadable Files',
            },
        ),
        migrations.CreateModel(
            name='DownloadableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(help_text='Name of this document group.', max_length=255)),
                ('group_description', wagtail.fields.RichTextField(blank=True, help_text='Optional group overview or description.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='downloadables.downloadableformspage')),
            ],
            options={
                'verbose_name': 'Downloadable Group',
                'verbose_name_plural': 'Downloadable Groups',
            },
        ),
        migrations.CreateModel(
            name='DownloadableSubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the subfile document.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional short description.')),
                ('file', models.ForeignKey(help_text='Upload the document file (PDF, DOCX, etc.).', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfiles', to='downloadables.downloadablegroup')),
                ('group_image', models.ForeignKey(blank=True, help_text='Optional image representing this group (e.g., workshop photo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Sub File',
                'verbose_name_plural': 'Sub Files',
            },
        ),
    ]
