# Generated by Django 5.2.6 on 2025-10-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadablesubfile',
            name='group_image',
        ),
        migrations.AddField(
            model_name='downloadablegroup',
            name='group_image',
            field=models.ForeignKey(blank=True, help_text='Optional image representing this group (e.g., workshop photo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
