# Generated by Django 5.2.6 on 2025-10-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_researcharticlepage_studentresearchpage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='FSUU BIRC', max_length=255)),
                ('phone_number', models.CharField(default='+91 123 654 7898', max_length=50)),
                ('address', models.TextField(default='San. Francisco St. Butuan City, Philippines')),
                ('email', models.EmailField(default='biodiversity@urios.edu.ph', max_length=254)),
                ('partner1_title', models.CharField(blank=True, max_length=255)),
                ('partner1_url', models.URLField(blank=True)),
                ('partner2_title', models.CharField(blank=True, max_length=255)),
                ('partner2_url', models.URLField(blank=True)),
                ('partner1_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('partner2_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
