# Generated by Django 5.2.6 on 2025-10-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_siteconfiguration'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='partner1_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='partner2_url',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partner1_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='partner2_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
