# Generated by Django 5.2.6 on 2025-10-05 01:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_siteconfiguration_partner1_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'BIRC CONTENT MENU'},
        ),
        migrations.AlterModelOptions(
            name='studentresearchpage',
            options={'verbose_name': 'Creating content page for URE'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_description',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='About the site'),
        ),
    ]
