# Generated by Django 5.2.6 on 2025-10-05 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='partner1_logo',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='partner1_page',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='partner1_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='partner2_logo',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='partner2_page',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='partner2_title',
        ),
    ]
