# Generated by Django 5.2.6 on 2025-10-05 01:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_siteconfiguration_partner1_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='site_config',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='home.siteconfiguration'),
        ),
    ]
