# Generated by Django 5.2.6 on 2025-10-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_studentresearchpage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitewidepage',
            options={'verbose_name': 'Creating pages for other purpose'},
        ),
        migrations.AlterField(
            model_name='sitewidepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='preferred size 190x214', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
