# Generated by Django 5.2.6 on 2025-10-07 08:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_collectionpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesDataTable',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('columns', models.JSONField(blank=True, help_text='Array of column names for the table', null=True, verbose_name='Column Names')),
            ],
            options={
                'verbose_name': 'Species Data Table',
                'verbose_name_plural': 'Species Data Tables',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpeciesDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.JSONField(blank=True, help_text='Array of cell values for this row', null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='home.speciesdatatable')),
            ],
            options={
                'verbose_name': 'Species Data Row',
                'verbose_name_plural': 'Species Data Rows',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['page', 'id'], name='home_specie_page_id_5c748b_idx')],
            },
        ),
    ]
