# Generated by Django 5.2.6 on 2025-10-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_speciesdatatable_description_speciesgalleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesgalleryimage',
            options={'verbose_name': 'Species Image', 'verbose_name_plural': 'Species Images'},
        ),
        migrations.AlterField(
            model_name='speciesgalleryimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption for the species image', max_length=255),
        ),
    ]
