# Generated by Django 5.2.6 on 2025-10-07 12:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_speciesgalleryimage_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'})})),
            ],
            options={
                'verbose_name': 'Species Profile',
                'verbose_name_plural': 'Species Profiles',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SepciesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', wagtail.fields.RichTextField(blank=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Creating pages for Natural History Collection only',
            },
            bases=('wagtailcore.page',),
        ),
    ]
