# Generated by Django 5.2.6 on 2025-10-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_speciesprofilepage_sepciespage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sepciespage',
            options={'verbose_name': 'Creating pages for Species Profile Only'},
        ),
    ]
