# Generated by Django 5.2.6 on 2025-10-07 12:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_sepciespage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesprofilepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('page_link', 4), ('external_url', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.CharBlock', (), {'form_classname': 'quote-block', 'help_text': 'Short quote', 'label': 'Quote'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page Link'}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'external link', 'label': 'External URL'})}),
        ),
    ]
