# Generated by Django 5.2.6 on 2025-10-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_speciesprofilepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesprofilepage',
            name='subtitle',
        ),
    ]
