# Generated by Django 5.2.6 on 2025-10-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_speciesprofilepage_subtitle'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesgalleryimage',
            name='pagelink',
            field=models.ForeignKey(blank=True, help_text='Optional page link for this species information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
