# Generated by Django 5.2.6 on 2025-10-07 12:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_speciesgalleryimage_pagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesprofilepage',
            name='body',
            field=wagtail.fields.StreamField([('heading_h1', 0), ('heading_h2', 1), ('heading_h3', 2), ('paragraph', 3), ('image', 4), ('quote', 5), ('page_link', 6), ('external_url', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Heading H1'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Heading H2'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Heading H3'}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraph'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'quote-block', 'help_text': 'Short quote', 'label': 'Quote'}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page Link'}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'external link', 'label': 'External URL'})}),
        ),
    ]
