# Generated by Django 5.2.6 on 2025-10-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_speciesprofilepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharticlepage',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='Thumbnail image for listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
