# Generated by Django 5.2.6 on 2025-10-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_facultyarticlepage_facultyresearchpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyresearchpage',
            options={'verbose_name': 'Creating pages for Faculty Research only'},
        ),
    ]
