# Generated by Django 5.2.6 on 2025-10-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_collaborationarticlepage_collaborationresearchpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='developed_by',
            field=models.TextField(default='© 2025 FSUU BIRC WEBSITE. All Rights Reserved | Developed by BIRC TEAM', verbose_name='Developed By'),
        ),
    ]
