# Generated by Django 5.2.6 on 2025-10-08 01:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_siteconfiguration_developed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFieldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption1', models.CharField(blank=True, max_length=100)),
                ('value1', models.CharField(blank=True, max_length=100)),
                ('icon1', models.CharField(blank=True, help_text='Bootstrap icon class, e.g., "bi-calendar-check me-2"', max_length=100)),
                ('caption2', models.CharField(blank=True, max_length=100)),
                ('value2', models.CharField(blank=True, max_length=100)),
                ('icon2', models.CharField(blank=True, max_length=100)),
                ('caption3', models.CharField(blank=True, max_length=100)),
                ('value3', models.CharField(blank=True, max_length=100)),
                ('icon3', models.CharField(blank=True, max_length=100)),
                ('caption4', models.CharField(blank=True, max_length=100)),
                ('value4', models.CharField(blank=True, max_length=100)),
                ('icon4', models.CharField(blank=True, max_length=100)),
                ('caption5', models.CharField(blank=True, max_length=100)),
                ('value5', models.CharField(blank=True, max_length=100)),
                ('icon5', models.CharField(blank=True, max_length=100)),
                ('caption6', models.CharField(blank=True, max_length=100)),
                ('value6', models.CharField(blank=True, max_length=100)),
                ('icon6', models.CharField(blank=True, max_length=100)),
                ('site_config', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_field_items', to='home.siteconfiguration')),
            ],
            options={
                'verbose_name': 'Generic Item',
                'verbose_name_plural': 'Generic Items',
            },
        ),
    ]
