# Generated by Django 5.2.6 on 2025-10-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_genericfielditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfielditem',
            name='icon1',
            field=models.CharField(blank=True, choices=[('bi-calendar-check me-2', 'Calendar Check'), ('bi-clock me-2', 'Clock'), ('bi-binoculars me-2', 'Binoculars'), ('bi-slash-circle me-2', 'Slash Circle'), ('bi-geo-alt me-2', 'Location'), ('bi-person me-2', 'Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='genericfielditem',
            name='icon2',
            field=models.CharField(blank=True, choices=[('bi-calendar-check me-2', 'Calendar Check'), ('bi-clock me-2', 'Clock'), ('bi-binoculars me-2', 'Binoculars'), ('bi-slash-circle me-2', 'Slash Circle'), ('bi-geo-alt me-2', 'Location'), ('bi-person me-2', 'Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='genericfielditem',
            name='icon3',
            field=models.CharField(blank=True, choices=[('bi-calendar-check me-2', 'Calendar Check'), ('bi-clock me-2', 'Clock'), ('bi-binoculars me-2', 'Binoculars'), ('bi-slash-circle me-2', 'Slash Circle'), ('bi-geo-alt me-2', 'Location'), ('bi-person me-2', 'Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='genericfielditem',
            name='icon4',
            field=models.CharField(blank=True, choices=[('bi-calendar-check me-2', 'Calendar Check'), ('bi-clock me-2', 'Clock'), ('bi-binoculars me-2', 'Binoculars'), ('bi-slash-circle me-2', 'Slash Circle'), ('bi-geo-alt me-2', 'Location'), ('bi-person me-2', 'Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='genericfielditem',
            name='icon5',
            field=models.CharField(blank=True, choices=[('bi-calendar-check me-2', 'Calendar Check'), ('bi-clock me-2', 'Clock'), ('bi-binoculars me-2', 'Binoculars'), ('bi-slash-circle me-2', 'Slash Circle'), ('bi-geo-alt me-2', 'Location'), ('bi-person me-2', 'Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='genericfielditem',
            name='icon6',
            field=models.CharField(blank=True, choices=[('bi-calendar-check me-2', 'Calendar Check'), ('bi-clock me-2', 'Clock'), ('bi-binoculars me-2', 'Binoculars'), ('bi-slash-circle me-2', 'Slash Circle'), ('bi-geo-alt me-2', 'Location'), ('bi-person me-2', 'Person')], max_length=50),
        ),
    ]
