# Generated by Django 5.2.6 on 2025-10-08 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_genericfielditem_icon1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfielditem',
            name='site_config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generic_fields', to='home.siteconfiguration'),
        ),
    ]
