# Generated by Django 5.2.6 on 2025-10-08 02:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_genericfielditem_site_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfielditem',
            name='site_config',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_fields', to='home.siteconfiguration'),
        ),
    ]
