# Generated by Django 5.2.6 on 2025-10-08 22:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_genericfielditem_site_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepciespage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction text for this species'),
        ),
    ]
