# Generated by Django 5.2.6 on 2025-10-08 22:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_sepciespage_intro_speciesprofilepage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesprofilepage',
            name='intro',
        ),
        migrations.AddField(
            model_name='speciesgalleryimage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction text for this species'),
        ),
    ]
