# Generated by Django 5.2.6 on 2025-10-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_speciesprofilepage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_additional_info',
            field=models.TextField(default='', verbose_name='A caption footer additional information for all site wide footer article page'),
        ),
    ]
