# Generated by Django 5.2.6 on 2025-10-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_siteconfiguration_footer_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_additional_info',
            field=models.TextField(blank=True, default='', verbose_name='A caption footer additional information for all site wide footer article page'),
        ),
    ]
