# Generated by Django 5.2.6 on 2025-10-09 01:05

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_siteconfiguration_footer_additional_info'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVisionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fsuu_mission_title', models.CharField(default='FSUU Mission', max_length=255)),
                ('fsuu_mission_content', wagtail.fields.RichTextField(blank=True)),
                ('fsuu_vision_title', models.CharField(default='FSUU Vision', max_length=255)),
                ('fsuu_vision_content', wagtail.fields.RichTextField(blank=True)),
                ('fsuu_body', wagtail.fields.RichTextField(blank=True)),
                ('birc_mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('birc_mission_content', wagtail.fields.RichTextField(blank=True)),
                ('birc_vision_title', models.CharField(default='Our Vision', max_length=255)),
                ('birc_vision_content', wagtail.fields.RichTextField(blank=True)),
                ('birc_body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mission & Vision Page',
                'verbose_name_plural': 'Mission & Vision Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the personnel', max_length=255)),
                ('position', models.CharField(help_text='Job title or position', max_length=255)),
                ('department', models.CharField(blank=True, help_text='Department or unit', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50)),
                ('bio', wagtail.fields.RichTextField(blank=True, help_text='Short biography or description')),
                ('order', models.IntegerField(default=0, help_text='Ordering number')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_items', to='home.missionvisionpage')),
                ('photo', models.ForeignKey(blank=True, help_text='Profile photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['order', 'name'],
            },
        ),
    ]
