# Generated by Django 5.2.6 on 2025-10-09 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_missionvisionpage_personnel'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionvisionpage',
            name='birc_logo',
            field=models.ForeignKey(blank=True, help_text='Biodiversity Informatics Research Center Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='missionvisionpage',
            name='fsuu_logo',
            field=models.ForeignKey(blank=True, help_text='Father Saturnino Urios University Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
