# Generated by Django 5.2.6 on 2025-10-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_missionvisionpage_birc_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='birc_mv_caption',
            field=models.TextField(blank=True, default='Biodiversity Informatics Research Center', verbose_name='BIRC mision and vision caption'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='fsuu_mv_caption',
            field=models.TextField(blank=True, default='Father Saturnino Urios University', verbose_name='FSUU mision and vision caption'),
        ),
    ]
