# Generated by Django 5.2.6 on 2025-10-09 02:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_siteconfiguration_mv_ourteam_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mv_ourteam_caption',
            field=models.TextField(blank=True, default='Our Team', verbose_name='Team Title'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mv_ourteam_description',
            field=wagtail.fields.RichTextField(blank=True, default='Meet the dedicated individuals behind our mission', help_text='Introduction text for this species', verbose_name='Team Short Description'),
        ),
    ]
