# Generated by Django 5.2.6 on 2025-10-09 04:05

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_siteconfiguration_mv_ourteam_caption_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperMasterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Swiper page',
                'verbose_name_plural': 'Swiper pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SwiperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature Name', max_length=795)),
                ('alt_name', models.CharField(help_text='Feature alternate name or intro', max_length=795)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Description')),
                ('order', models.IntegerField(default=0, help_text='Ordering number')),
                ('image', models.ForeignKey(blank=True, help_text='Image for the feature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiper_items', to='home.swipermasterpage')),
            ],
            options={
                'verbose_name': 'Swiper Data',
                'verbose_name_plural': 'Swiper Data',
                'ordering': ['order', 'name'],
            },
        ),
    ]
