# Generated by Django 5.2.6 on 2025-10-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_swipermasterpage_swiperdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiperdata',
            name='alt_name',
            field=models.CharField(blank=True, help_text='Feature alternate name or intro', max_length=795),
        ),
    ]
