# Generated by Django 5.2.6 on 2025-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_swiperdata_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='lp_caption1',
            field=models.TextField(blank=True, default='Highlights 1', verbose_name='Landing page section caption 1'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='lp_caption2',
            field=models.TextField(blank=True, default='Highlights 2', verbose_name='Landing page section caption 2'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='lp_caption3',
            field=models.TextField(blank=True, default='Highlights 3', verbose_name='Landing page section caption 3'),
        ),
    ]
