# Generated by Django 5.2.6 on 2025-10-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactpage_options_alter_contactpage_intro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={},
        ),
    ]
